<?php
/**
 * New Account
 * $entity = The account owner
 * $code = The Code
 */
/**
 * Need to verify email address
 */
$emailVerificationEnabled = $entity->emailVerificationEnabled();

/**
 * Password was generated by the system
 */
$passwordAutoGenerate = $entity->passwordAutoGenerate();
?>
<?php echo zbase_view_render(zbase_view_file_contents('email.header')); ?>
<?php if(!empty($passwordAutoGenerate)): ?>
	<h1>Welcome to <?php echo zbase_site_name() ?></h1>

	<p>Below is your login information</p>
	<span>Name: <?php echo $entity->displayName() ?></span>
	<br />
	<span>Email: <?php echo $entity->email() ?></span>
	<br />
	<span>Password: <?php echo $attributes['raw_password'] ?></span>
	<br />
	<br />
	<a href="<?php echo zbase_url_from_route('login') ?>">Login Here</a>
<?php else: ?>
	<?php if(!empty($emailVerificationEnabled)): ?>
		<h1>Welcome to <?php echo zbase_site_name() ?></h1>

		<p>Below is your Email verification code</p>
		<span>Email: <?php echo $entity->email() ?></span>
		<br />
		<span>Code: <?php echo $code ?></span>
		<br />
		<br />
		<a href="<?php echo zbase_url_from_route('account', ['action' => 'email', 'task' => 'verify', 'e' => $entity->email(), 'c' => $code]) ?>">Click here to verify</a>

	<?php endif; ?>
<?php endif; ?>

	<?php echo zbase_view_render(zbase_view_file_contents('email.footer')); ?>